# Generated by Django 5.1 on 2024-10-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="cadastrarEquipamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codEquipamento", models.IntegerField()),
                ("nomeEquipamento", models.CharField(max_length=100)),
            ],
        ),
    ]
