# Generated by Django 5.1 on 2024-10-01 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_produtos", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cadastrarequipamento",
            old_name="codEquipamento",
            new_name="cod_equipamento",
        ),
        migrations.RenameField(
            model_name="cadastrarequipamento",
            old_name="nomeEquipamento",
            new_name="nome_equipamento",
        ),
    ]
