# Generated by Django 5.1 on 2024-10-01 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_produtos",
            "0002_rename_codequipamento_cadastrarequipamento_cod_equipamento_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CadastrarColaborador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_colaborador", models.CharField(max_length=100)),
                ("cpf", models.CharField(max_length=11)),
                ("cargo", models.CharField(max_length=100)),
                ("setor", models.CharField(max_length=100)),
            ],
        ),
    ]
