# Generated by Django 5.1 on 2024-10-01 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_produtos", "0003_cadastrarcolaborador"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegistrarAcao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_colaborador", models.CharField(max_length=100)),
                ("nome_equipamento", models.CharField(max_length=100)),
                ("data_emprestimo", models.DateField()),
                ("data_prevista_devolução", models.DateField()),
                ("status", models.CharField(max_length=100)),
                ("condicoes", models.CharField(max_length=100)),
            ],
        ),
    ]
