# Generated by Django 5.1 on 2024-10-01 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_produtos", "0004_registraracao"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registraracao",
            old_name="data_prevista_devolução",
            new_name="data_prevista_devolucao",
        ),
    ]
