# Generated by Django 5.1 on 2024-10-01 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "app_produtos",
            "0005_rename_data_prevista_devolução_registraracao_data_prevista_devolucao",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ColaboradorEquipamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "colaborador_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_produtos.cadastrarcolaborador",
                    ),
                ),
                (
                    "data_emprestimo_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_produtos.registraracao",
                    ),
                ),
                (
                    "equipamento_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_produtos.cadastrarequipamento",
                    ),
                ),
            ],
        ),
    ]
