# Generated by Django 5.1 on 2024-10-02 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_produtos", "0006_colaboradorequipamento"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="registraracao",
            name="nome_colaborador",
        ),
        migrations.RemoveField(
            model_name="registraracao",
            name="nome_equipamento",
        ),
        migrations.AddField(
            model_name="registraracao",
            name="colaborador_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app_produtos.cadastrarcolaborador",
            ),
        ),
        migrations.AddField(
            model_name="registraracao",
            name="equipamento_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app_produtos.cadastrarequipamento",
            ),
        ),
        migrations.DeleteModel(
            name="ColaboradorEquipamento",
        ),
    ]
