# Generated by Django 5.1 on 2024-11-09 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_produtos", "0008_registraracao_data_devolucao_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="cadastrarLogin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=140)),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
    ]
